### ISSUE TITLE
Undefined variable $getPrefixIconColor

### ISSUE THREAD

**Issue by henokyehulu** [marvinosswald/filament-input-select-affix#5]
Copied the exact "example code" to my project  but I got this error. Please help.

**Comment by marvinosswald** [comment]
Hi henokyehulu,

sorry for the delay ( i didn't get a notification about your issue). This sounds to me like a version mismatch.
What filament version are you using ? Please keep in mind this plugin is **only compatible with 3.x**.

**Comment by marvinosswald** [comment]
this issue has been stale for more than a month now, please report back if this issue still persists.
