### ISSUE TITLE
Select value not passed when used in a modal

### ISSUE THREAD

**Issue by Yann-iBroStudio** [marvinosswald/filament-input-select-affix#6]
Hi,

I use a TextInputSelectAffix field in a ManageRelatedRecords page. The form is displayed in a modal.

When I submit the form, the select field is not in the data array, only the input text is present.

**Comment by marvinosswald** [comment]
@Yann-iBroStudio sorry for my late reply. 

Can you provide me with some example code?

**Comment by marvinosswald** [comment]
unresponsive
