### ISSUE TITLE
->native(false) is not working.

### ISSUE THREAD

**Issue by 0samaKamel** [marvinosswald/filament-input-select-affix#7]
Thanks for your work,
Native select is fine, but ->native(false) is not working.

**Comment by marvinosswald** [comment]
Hi @0samaKamel,

the problem seems to be an `overflow-hidden` which is part of every `TextInput` it appears.
I've removed this now, as i don't see a very good reason at the moment for it.

If anyone uses this and finds this causes issues for them please let me know.
